---
- name: Download Node Exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-1.8.2.linux-amd64.tar.gz"

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-1.8.2.linux-amd64.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes
    creates: "/usr/local/bin/node_exporter-1.8.2.linux-amd64/node_exporter"

- name: Move binary to "/usr/local/bin/
  ansible.builtin.command:
    cmd: mv /usr/local/bin/node_exporter-1.8.2.linux-amd64/node_exporter /usr/local/bin/node_exporter
  args:
    creates: "/usr/local/bin/node_exporter"

- name: Create Node Exporter systemd service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=root
      ExecStart=/usr/local/bin/node_exporter
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
    mode: "0644"

- name: Reload systemd to apply changes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start and enable Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes
    state: restarted
