---
- name: Update apt-get repo and cache
  apt:
    update_cache: yes

- name: Install redis
  apt:
    name: redis-server
    state: present

- name: Update redis configuration
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^protected-mode'
    line: 'protected-mode no'
    state: present
    backup: yes

- name: Bind default address
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind'
    line: 'bind 0.0.0.0 ::1'
    state: present
    backup: yes

- name: Start redis
  service:
    name: redis-server
    state: started
    enabled: yes
