---
- name: Install required packages
  apt:
    name:
      - wget
      - tar
    state: present

- name: Create prometheus user
  user:
    name: prometheus
    shell: /usr/sbin/nologin

- name: Create directories for prometheus
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  with_items: 
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.55.0-rc.0/prometheus-2.55.0-rc.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move Prometheus binaries
  copy:
    src: /tmp/prometheus-2.55.0-rc.0.linux-amd64/{{ item }}
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'
  with_items:
    - prometheus
    - promtool

- name: Copy prometheus configuration
  copy:
    src: /tmp/prometheus-2.55.0-rc.0.linux-amd64/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    remote_src: yes

- name: Create Prometheus systemd service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus/ \
        --web.console.templates=/usr/share/prometheus/consoles \
        --web.console.libraries=/usr/share/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target

- name: Reload system
  systemd:
    daemon_reload: yes
  notify: Restart prometheus

- name: Enable and start Prometheus service
  systemd:
    name: prometheus
    enabled: yes
    state: restarted