---
postgresql_python_library: python3-psycopg2
postgresql_restarted_state: "restarted"
postgresql_user: postgres
postgresql_group: postgres
postgresql_unix_socket_directories:
  - /var/run/postgresql

postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: log_directory
    value: 'log'

postgresql_packages:
  - postgresql
  - postgresql-contrib
  - libpq-dev
  - python3-psycopg2

postgresql_locales:
  - 'en_US.UTF-8'
postgresql_version: "13"
postgresql_daemon: postgresql
postgresql_data_dir: "/var/lib/pgsql/data"
postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
postgresql_config_path: "/var/lib/pgsql/data"
postgresql_log_dir: "{{ (postgresql_global_config_options | items2dict(key_name='option', value_name='value')).log_directory }}"
postgresql_effective_log_dir: '{{ postgresql_data_dir }}/{{ postgresql_log_dir }}'
postgresql_unix_socket_directories_mode: '0755'
postgresql_service_state: started
postgresql_service_enabled: true
postgresql_users:
  - name: postgres
    password: password
postgres_users_no_log: true
postgresql_auth_method: 'md5'
postgresql_databases:
  - name: postgres

postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: "{{ postgresql_auth_method }}"}
  - {type: local, database: all, user: all, auth_method: "{{ postgresql_auth_method }}"}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: "{{ postgresql_auth_method }}"}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: "{{ postgresql_auth_method }}"}

  # postgres_user: "postgres"
postgres_password: "password"
postgres_db: "postgres"
postgres_host: "localhost"
postgres_port: "5432"
# postgres_version: "13"
# postgresql_bin_path: "/usr/lib/postgresql/{{ postgres_version }}/bin"
# postgresql_data_dir: "/var/lib/postgresql/{{ postgres_version }}/main"
postgresql_conf_dir: "/etc/postgresql/{{ postgres_version }}/main"
# ansible_ssh_pipelining: true
db_backup_filename: "data.dump"