---
tomcat_version: "9.0.95"
tomcat_install_dir: "/opt/tomcat"
tomcat_user: "tomcat"
tomcat_group: "tomcat"
tomcat_download_url: "https://dlcdn.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
