---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Java
  apt:
    name: default-jdk
    state: present

- name: Install Tomcat 9
  apt:
    name: tomcat9
    state: present

- name: 4. Create directory for application
  file:
    path: /var/lib/tomcat9/webapps
    state: directory
    owner: tomcat
    group: tomcat

- name: Ensure that Tomcat is started and enabled
  service:
    name: tomcat9
    state: started
    enabled: yes

- name: Create schedule_logs directory
  file:
    path: '/var/lib/tomcat9/schedule_logs'
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0777'
  become: true

- name: Remove the default ROOT directory if it exists
  file:
    path: /var/lib/tomcat9/webapps/ROOT
    state: absent

- name: Deploy WAR file to Tomcat
  copy:
    src: files/ROOT.war
    dest: /var/lib/tomcat9/webapps/
    owner: tomcat
    group: tomcat

- name: Restart Tomcat service
  service:
    name: tomcat9
    state: restarted
